name: Jekyll site CI

on:
  push:
    branches: [ "Wolfmanbunnydeer/cmc2392kittty.github.io/blob/Art/test/images/index(1)(2).html" ]
  pull_request:
    branches: [ "Wolfmanbunnydeer/cmc2392kittty.github.io/blob/Art/test/images/index(1)(2).html" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
